### ISSUE TITLE
Replace ring?

### ISSUE THREAD

**Issue by rushmorem** [tomprogrammer/scram#8]
Have you considered replacing ring? I keep running into all sorts of issues with this library every now and then because of its dependency on ring. For example, it breaks with every major ring release.

**Comment by tomprogrammer** [comment]
Initially I thought about supporting multiple security libraries you can choose via cargo features. There are many libraries out there for SHA256 and its variants as well as PBKDF2.

I think support for openssl and schannel (if it exposes both algorithms) would be a good first step. Which library do you wish this crate should depend on?

**Comment by rushmorem** [comment]
I don't have any particular preference but at least one of my dependencies is using openssl.

**Comment by rushmorem** [comment]
This issue should go away in ring 0.13.

**Comment by rushmorem** [comment]
Since we are now using ring 0.13, this shouldn't be an issue any more.
